### ISSUE TITLE
Meetup date is printed loads of times for with javascript off (previously for a split second on page-load)

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/react.london#297]
Found by @sarigriffiths 

Repro:

- Go to meetup.react.london

On page load you'll see this for a split second:

![screen shot 2017-01-16 at 13 02 07](https://cloud.githubusercontent.com/assets/22592849/21984079/1b274e96-dbec-11e6-99cb-f9613ba7293b.png)

**Comment by JRGranell** [comment]
On it like a car bonnet!

**Comment by sarigriffiths** [comment]
Wow. That's A LOT more than I've seen!

**Comment by samsmith1983** [comment]
This was fixed as part of PR #298 

Closing.

**Comment by asavin** [comment]
Reopening this as it is still reproducible with live data

**Comment by samsmith1983** [comment]
Also, javascript must be disabled to repro this

**Comment by sarigriffiths** [comment]
This is still happening when I open the page in Chrome incognito.
